# Generated by Django 5.1.3 on 2025-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='check_in_photos/%Y/%m/%d/', verbose_name='รูปถ่ายเช็คอิน'),
        ),
    ]
