# Generated by Django 5.1.3 on 2025-02-18 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'ป่วย'), ('personal', 'กิจส่วนตัว'), ('vacation', 'พักร้อน'), ('other', 'อื่นๆ')], default=django.utils.timezone.now, max_length=20, verbose_name='ประเภทการลา'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='เหตุผลการลา'),
        ),
    ]
