# Generated by Django 5.1.3 on 2025-02-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_leaverequest_approved_at_leaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
